name: Example
options:
  bundleIdPrefix: com.twigcodes
  minimumXcodeGenVersion: 2.0.0
configFiles:
  Local: IDEConfig/LocalConfig.xcconfig
  Dev: IDEConfig/DevConfig.xcconfig
  Prod: IDEConfig/ProdConfig.xcconfig
configs:
  Local: debug
  Dev: debug
  Prod: release
targets:
  Example:
    type: application
    platform: iOS
    deploymentTarget: '9.0'
    sources: [Example]
    configVariants:
      - Local
      - Dev
      - Prod
    settings:
      configs:
        Local:
          DEBUG_MODE: YES
        Dev:
          DEBUG_MODE: YES
        Prod:
          DEBUG_MODE: NO
    postBuildScripts:
      - path: Scripts/uploadSymbolToBugly.sh
        name: Upload Symbol To Bugly
