# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_version_number(
      bump_type: "patch" # Automatically increment patch version number
    )
    build_app(
      configuration: "Release",
      workspace: "Example.xcworkspace",
      scheme: "Example")
    upload_to_testflight
  end
  desc "make release build"
  lane :release do

    # invokes cert
    get_certificates(
      username: "wpcfan@gmail.com"
    )
    # invokes sigh
    get_provisioning_profile(
      development: "false",
      force: true,
      app_identifier: "com.twigcodes.Example",
      username: "wpcfan@gmail.com"
    )
    disable_automatic_code_signing(path: "Example.xcodeproj")
    build_app(scheme: "Example",
              configuration: "Release",
              workspace: "Example.xcworkspace",
              include_bitcode: false)
    enable_automatic_code_signing(path: "Example.xcodeproj")
    upload_to_testflight
  end
end
