# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_push_certificate
    sync_code_signing(type: "appstore")
    increment_build_number
    build_app(
      include_bitcode: true,
      configuration: "Release",
      workspace: "Example.xcworkspace",
      scheme: "Example")
    upload_to_testflight
  end
  desc "make release build"
  lane :release do
    get_push_certificate
    sync_code_signing(type: "appstore")
    increment_version_number(
      bump_type: "patch" # Automatically increment patch version number
    )
    build_app(scheme: "Example",
              configuration: "Release",
              workspace: "Example.xcworkspace",
              include_bitcode: false)
  end
end
