# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "make release build"
  lane :dev do
    # invokes cert
    get_certificates(
      development: "true",
      username: "wpcfan@gmail.com"
    )
    # invokes sigh
    get_provisioning_profile(
      development: "true",
      app_identifier: "com.twigcodes.Example-dev",
      username: "wpcfan@gmail.com"
    )
    disable_automatic_code_signing(path: "Example.xcodeproj")
    build_app(scheme: "Dev",
              configuration: "Debug",
              workspace: "Example.xcworkspace",
              include_bitcode: true)
    enable_automatic_code_signing(
      path: "Example.xcodeproj",
      bundle_identifier: "com.twigcodes.Example-dev"
      )
  end
  desc "make release build"
  lane :release do

    # invokes cert
    get_certificates(
      username: "wpcfan@gmail.com"
    )
    # invokes sigh
    get_provisioning_profile(
      app_identifier: "com.twigcodes.Example",
      username: "wpcfan@gmail.com"
    )
    disable_automatic_code_signing(path: "Example.xcodeproj")
    build_app(scheme: "Example",
              workspace: "Example.xcworkspace",
              include_bitcode: true)
    enable_automatic_code_signing(path: "Example.xcodeproj")
    upload_to_testflight
  end
end
