//
//  SmartApiType.swift
//  Example
//
//  Created by 王芃 on 2019/1/25.
//  Copyright © 2019 twigcodes. All rights reserved.
//

public enum SmartApiType {
    case register
    case setdevicetoken
    case getCaptcha
    case home
    case messageTypes
    case messages
    case delMessage
    case weather
    case analytics
    case sideMenuItems
    case sceneSort
    case prefDevicePushState
    case setPerfDevicePushState
    case getAirDetector
    case setAirDetector
    case currentAirDetector
    case validateCaptcha
    case sendSms
    case directSendSms
    case validateSmsCode
    case setPassword
    case changeMobile
    case bindJdAccount
    case login
    case logout
    case profile
    case updateProfile
    case updateAvatar
    case myHouses
    case bindHouse
    case unbindHouse
    case getHouseName
    case feedback
    case messageState
    case preferenceMsgState
    case familyMembers
    case familySearch
    case familyInvitaion
    case familySetupRelationship
    case familyRepsonseToInvitation
    case familyLiftRelationship
    case familyShare
    case familySharedItems
    case rooms
    case addRoom
    case delRoom
    case renameRoom
    case orderRooms
    case roomDevices
    case roomUnassignedDevices
    case addDeviceToRoom
    case delDeviceFromRoom
    case bindDevice
    case renameDevice
    case unbindDevice
    case devices
    case deviceInfo
    case projects
    case floorAndUnits
    case houseNos
    case deviceToAccept
    case acceptanceStatus
    case houseAcceptanceStatus
    case operations
    case clearOperations
    case delOperation
    case scenes
    case addScene
    case updateScene
    case delScene
    case verifyScene
    var entityPath: String {
        switch self {
        case .register:
            return "/phoneinfo/register"
        case .setdevicetoken:
            return "/phoneinfo/setdevicetoken"
        case .getCaptcha:
            return "/phoneinfo/getverifycode"
        case .home:
            return "/home/homeinfo"
        case .messageTypes:
            return "/home/messagetypelist"
        case .messages:
            return "/home/messagelist"
        case .delMessage:
            return "/home/delmessage"
        case .weather:
            return "/home/weatherinfo"
        case .analytics:
            return "/home/takenotes"
        case .sideMenuItems:
            return "/home/menunum"
        case .sceneSort:
            return "/home/sort"
        case .prefDevicePushState:
            return "/home/devicepushstate"
        case .setPerfDevicePushState:
            return "/home/setdevicepushstate"
        case .getAirDetector:
            return "/home/grouphj"
        case .setAirDetector:
            return "/home/setgrouphj"
        case .currentAirDetector:
            return "/home/currentgrouphj"
        case .validateCaptcha:
            return "/user/validatepiccode"
        case .sendSms:
            return "/user/sendmsg"
        case .directSendSms:
            return "/user/onlySendMsg"
        case .validateSmsCode:
            return "/user/validatecode"
        case .setPassword:
            return "/user/setpassword"
        case .changeMobile:
            return "/user/updatephone"
        case .bindJdAccount:
            return "/user/bindaccount"
        case .login:
            return "/user/login"
        case .logout:
            return "/user/logout"
        case .profile:
            return "/user/userinfo"
        case .updateProfile:
            return "/user/updateuserinfo"
        case .updateAvatar:
            return "/user/updateavatar"
        case .myHouses:
            return "/user/myHouses"
        case .bindHouse:
            return "/user/bindhouse"
        case .unbindHouse:
            return "/user/unbindhouse"
        case .getHouseName:
            return "/user/gethousename"
        case .feedback:
            return "/user/feedback"
        case .messageState:
            return "/user/messagestate"
        case .preferenceMsgState:
            return "/user/setmessagestate"
        case .familyMembers:
            return "/family/memberlist"
        case .familySearch:
            return "/family/search"
        case .familyInvitaion:
            return "/family/invitation"
        case .familySetupRelationship:
            return "/family/familyinfo"
        case .familyRepsonseToInvitation:
            return "/family/invitereply"
        case .familyLiftRelationship:
            return "/family/relieve"
        case .familyShare:
            return "/family/addshare"
        case .familySharedItems:
            return "/family/sharelist"
        case .rooms:
            return "/room/grouplist"
        case .addRoom:
            return "/room/addgroup"
        case .delRoom:
            return "/room/remove"
        case .renameRoom:
            return "/room/rename"
        case .orderRooms:
            return "/room/groupsort"
        case .roomDevices:
            return "/room/groupdevices"
        case .roomUnassignedDevices:
            return "/room/nogroupdevices"
        case .addDeviceToRoom:
            return "/room/addtogroup"
        case .delDeviceFromRoom:
            return "/room/deldevice"
        case .bindDevice:
            return "/device/binding"
        case .renameDevice:
            return "/device/rename"
        case .unbindDevice:
            return "/device/relieveBinding"
        case .devices:
            return "/device/devicelist"
        case .deviceInfo:
            return "/device/deviceinfo"
        case .projects:
            return "/device/checkerprojectinfos"
        case .floorAndUnits:
            return "/device/floorandunitno"
        case .houseNos:
            return "/device/housenos"
        case .deviceToAccept:
            return "/device/checkerdevices"
        case .acceptanceStatus:
            return "/device/checkerstate"
        case .houseAcceptanceStatus:
            return "/device/housestate"
        case .operations:
            return "/operation/list"
        case .clearOperations:
            return "/operation/delall"
        case .delOperation:
            return "/operation/deloperation"
        case .scenes:
            return "/scene/list"
        case .addScene:
            return "/scene/addscene"
        case .updateScene:
            return "/scene/updatescene"
        case .delScene:
            return "/scene/delscene"
        case .verifyScene:
            return "/scene/verifyscene"
        }
    }
}
